lend-35-polygon-support
xave-finance/lending-market-v1 pull request #22
Opened 2022-06-16 03:27 UTC by tracyarciaga

## Description of Changes

Added halo-matic markets and configs and deploys scripts for Polygon 

[Link to Jira Ticket](https://halodao.atlassian.net/browse/LEND-35)

## How To Test

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2022-06-16 03:54 UTC, 0xAplki reviewed
I guess to fix your error we can add atleast 1 GWEI on maxPriorityFee

Here's my proposed workaround:
1 - add a const for `NETWORK_DEFAULT_PRIORITYFEE` and pattern in like `NETWORKS_DEFAULT_GAS`. set everything to 1 * GWEI (found in `helper-hardhat-config.ts`)
2 - add  `maxPriorityFeePerGas` param in `getCommonNetworkConfig` on `hardhat.config.ts` with the value `NETWORK_DEFAULT_PRIORITYFEE[networkName]`


Let see if this works!

2022-06-16 03:57 UTC, 0xAplki commented on markets/halo-matic/commons.ts
> +  IncentivesController: {
can we have this zero for now since we dont have it

2022-06-16 03:57 UTC, 0xAplki commented on markets/halo-matic/constants.ts
> +    lendingPoolAddress: '0xC73b2c6ab14F25e1EAd3DE75b4F6879DEde3968E',
we already deployed this?

2022-06-16 06:05 UTC, 0xAplki approved these changes

2022-07-11 16:15 UTC, 0xAplki commented
pls resolve conflicts

2022-07-11 16:16 UTC, 0xAplki requested changes
Pls resolve conflicts

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/commons.ts
> +    [ePolygonNetwork.matic]: '0xA39599424642D9fD35e475EF802EddF798dc555B',
```suggestion
    [ePolygonNetwork.matic]: '0xeEc23b994F27B6914A06180c6B5FA4f83ec80712',
```

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/commons.ts
> +    [ePolygonNetwork.matic]: '0x17F73aEaD876CC4059089ff815EDA37052960dFB',
```suggestion
    [ePolygonNetwork.matic]: '0x5AE7Ef3118D3F8739BA5525534367757FEd03540',
```

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/constants.ts
> +    lendingPoolAddress: '',
```suggestion
    lendingPoolAddress: '0x51485c7278fa37f0f504F541f2755abda7715abf',
```

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/commons.ts
> +    [ePolygonNetwork.matic]: '',
```suggestion
    [ePolygonNetwork.matic]: '0x51485c7278fa37f0f504F541f2755abda7715abf',
```

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/commons.ts
> +    [ePolygonNetwork.matic]: '',
```suggestion
    [ePolygonNetwork.matic]: '0xBacdf66F391E9CB65C1D7CD3e506b6AEE5fA2F88',
```

2022-08-31 09:53 UTC, tracyarciaga commented on markets/halo-matic/commons.ts
> +    [ePolygonNetwork.matic]: '0x3ac4e9aa29940770aeC38fe853a4bbabb2dA9C19',
```suggestion
    [ePolygonNetwork.matic]: '0x2Ee7e1FE1B65600A3bD28B06d0b958B3b6cc4695',
```

2022-08-31 10:42 UTC, 0xAplki approved these changes

2022-08-31 10:43 UTC, 0xAplki approved these changes

2022-09-01 04:01 UTC, merged